CREATE TABLE roles(id text PRIMARY KEY);
CREATE TABLE permissions(id text PRIMARY KEY);
CREATE TABLE role_permissions(role_id text REFERENCES roles, permission_id text REFERENCES permissions, PRIMARY KEY(role_id,permission_id));
CREATE TABLE users(id serial PRIMARY KEY, username text UNIQUE NOT NULL, name text NOT NULL, password_hash text NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE TABLE user_roles(user_id int REFERENCES users,role_id text REFERENCES roles,PRIMARY KEY(user_id,role_id));
CREATE TABLE sessions(token_hash text PRIMARY KEY,user_id int REFERENCES users,expires_at timestamptz NOT NULL);
CREATE TABLE collection_areas(id serial PRIMARY KEY,name text UNIQUE NOT NULL);
CREATE TABLE collectors(id serial PRIMARY KEY,name text NOT NULL,active boolean DEFAULT true);
CREATE TABLE subscribers(id serial PRIMARY KEY,account_no text UNIQUE NOT NULL,name text NOT NULL,contact text NOT NULL DEFAULT '',address text NOT NULL,area_id int REFERENCES collection_areas,collector_id int REFERENCES collectors,billing_day int NOT NULL DEFAULT 1 CHECK(billing_day BETWEEN 1 AND 28),due_day int NOT NULL DEFAULT 15 CHECK(due_day BETWEEN 1 AND 28),status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE','TERMINATED','ARCHIVED')),notes text NOT NULL DEFAULT '',created_at timestamptz DEFAULT now());
CREATE TABLE service_plans(id serial PRIMARY KEY,code text UNIQUE NOT NULL,name text NOT NULL,type text NOT NULL CHECK(type IN ('Internet','Cable','Combo')),price bigint NOT NULL CHECK(price>=0),fee bigint DEFAULT 0,speed int,channels int,description text DEFAULT '',active boolean DEFAULT true);
CREATE TABLE service_accounts(id serial PRIMARY KEY,account_no text UNIQUE NOT NULL,subscriber_id int NOT NULL REFERENCES subscribers,plan_id int NOT NULL REFERENCES service_plans,address text NOT NULL,rate bigint NOT NULL CHECK(rate>=0),activation_date date NOT NULL,billing_start date NOT NULL,billing_day int DEFAULT 1 CHECK(billing_day BETWEEN 1 AND 28),due_day int DEFAULT 15 CHECK(due_day BETWEEN 1 AND 28),status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','SUSPENDED','TERMINATED')),collector_id int REFERENCES collectors);
CREATE TABLE billing_cycles(period date PRIMARY KEY,actor_id int REFERENCES users,created_at timestamptz DEFAULT now());
CREATE SEQUENCE invoice_number;
CREATE SEQUENCE receipt_number;
CREATE TABLE invoices(id serial PRIMARY KEY,number text UNIQUE NOT NULL,service_id int NOT NULL REFERENCES service_accounts,period date NOT NULL,due_date date NOT NULL,total bigint NOT NULL CHECK(total>=0),status text NOT NULL DEFAULT 'UNPAID' CHECK(status IN ('DRAFT','UNPAID','PARTIALLY_PAID','PAID','OVERDUE','VOID','CREDITED')),created_at timestamptz DEFAULT now(),UNIQUE(service_id,period));
CREATE TABLE invoice_items(id serial PRIMARY KEY,invoice_id int NOT NULL REFERENCES invoices,description text NOT NULL,amount bigint NOT NULL);
CREATE TABLE collection_batches(id serial PRIMARY KEY,collector_id int NOT NULL REFERENCES collectors,area_id int REFERENCES collection_areas,status text NOT NULL DEFAULT 'OPEN',expected bigint DEFAULT 0,created_at timestamptz DEFAULT now(),closed_by int REFERENCES users,CHECK(status IN ('OPEN','IN_PROGRESS','SUBMITTED','REMITTED','RECONCILED','CLOSED')));
CREATE TABLE batch_accounts(batch_id int REFERENCES collection_batches,subscriber_id int REFERENCES subscribers,expected bigint NOT NULL,PRIMARY KEY(batch_id,subscriber_id));
CREATE TABLE payment_proofs(id serial PRIMARY KEY,subscriber_id int NOT NULL REFERENCES subscribers,reference text UNIQUE NOT NULL,sender text NOT NULL,amount bigint NOT NULL CHECK(amount>0),path text,mime text,status text NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','VERIFIED','REJECTED')),reviewed_by int REFERENCES users,reviewed_at timestamptz,reason text,created_at timestamptz DEFAULT now());
CREATE TABLE payments(id serial PRIMARY KEY,subscriber_id int NOT NULL REFERENCES subscribers,receipt_no text UNIQUE NOT NULL,amount bigint NOT NULL CHECK(amount>0),method text NOT NULL CHECK(method IN ('Cash','GCash','Bank Transfer','Cheque','Other')),reference text,proof_id int UNIQUE REFERENCES payment_proofs,batch_id int REFERENCES collection_batches,actor_id int NOT NULL REFERENCES users,paid_at timestamptz NOT NULL DEFAULT now(),notes text DEFAULT '',reversed boolean DEFAULT false,idempotency_key text UNIQUE NOT NULL);
CREATE UNIQUE INDEX unique_gcash_reference ON payments(lower(reference)) WHERE method='GCash';
CREATE TABLE payment_allocations(id serial PRIMARY KEY,payment_id int NOT NULL REFERENCES payments,invoice_id int NOT NULL REFERENCES invoices,amount bigint NOT NULL CHECK(amount>0),UNIQUE(payment_id,invoice_id));
CREATE TABLE payment_reversals(id serial PRIMARY KEY,payment_id int UNIQUE NOT NULL REFERENCES payments,actor_id int NOT NULL REFERENCES users,reason text NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE adjustments(id serial PRIMARY KEY,invoice_id int NOT NULL REFERENCES invoices,amount bigint NOT NULL,reason text NOT NULL,actor_id int REFERENCES users,created_at timestamptz DEFAULT now());
CREATE TABLE collector_remittances(id serial PRIMARY KEY,batch_id int UNIQUE NOT NULL REFERENCES collection_batches,expected_cash bigint NOT NULL,remitted_cash bigint NOT NULL CHECK(remitted_cash>=0),difference bigint NOT NULL,notes text NOT NULL,actor_id int REFERENCES users,created_at timestamptz DEFAULT now());
CREATE TABLE service_events(id serial PRIMARY KEY,service_id int NOT NULL REFERENCES service_accounts,kind text NOT NULL,reason text NOT NULL,actor_id int REFERENCES users,created_at timestamptz DEFAULT now());
CREATE TABLE suspension_records(id serial PRIMARY KEY,service_id int NOT NULL REFERENCES service_accounts,reason text NOT NULL,approved_by int REFERENCES users,effective_date date NOT NULL);
CREATE TABLE reconnection_records(id serial PRIMARY KEY,service_id int NOT NULL REFERENCES service_accounts,technician_id int REFERENCES users,fee bigint DEFAULT 0,requested_at timestamptz DEFAULT now(),completed_at timestamptz);
CREATE TABLE audit_logs(id bigserial PRIMARY KEY,actor_id int REFERENCES users,action text NOT NULL,entity text NOT NULL,entity_id text,reason text,old_value jsonb,new_value jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE application_settings(key text PRIMARY KEY,value jsonb NOT NULL);
CREATE TABLE backup_history(id serial PRIMARY KEY,filename text NOT NULL,sha256 text NOT NULL,status text NOT NULL,actor_id int REFERENCES users,created_at timestamptz DEFAULT now());
CREATE INDEX subscriber_search ON subscribers(lower(name),account_no,contact);
CREATE INDEX service_subscriber ON service_accounts(subscriber_id);
CREATE INDEX invoice_due ON invoices(due_date,status);
CREATE INDEX payment_date ON payments(paid_at);
CREATE INDEX payment_subscriber ON payments(subscriber_id);
CREATE INDEX allocation_invoice ON payment_allocations(invoice_id);
CREATE INDEX subscriber_assignment ON subscribers(collector_id,area_id);
CREATE INDEX audit_date ON audit_logs(created_at);
CREATE VIEW invoice_balances AS SELECT i.*,s.subscriber_id,s.plan_id,COALESCE((SELECT sum(a.amount) FROM adjustments a WHERE a.invoice_id=i.id),0)::bigint AS adjusted, (i.total+COALESCE((SELECT sum(a.amount) FROM adjustments a WHERE a.invoice_id=i.id),0)-COALESCE((SELECT sum(pa.amount) FROM payment_allocations pa JOIN payments p ON p.id=pa.payment_id WHERE pa.invoice_id=i.id AND NOT p.reversed),0))::bigint AS balance FROM invoices i JOIN service_accounts s ON s.id=i.service_id;
